 This will be called when any exception is thrown. 