public synchronized Exception getError(){
    return mException;
}